name: Build on Tag

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: wolverine998/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Joyeuse-Stock-Kernel
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r433403
        defconfig: joyeuse_defconfig
        image: Image.gz-dtb

    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
