name: Build on push master

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: wolverine998/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Xiaomi Kernel
      with:
        arch: arm64
        compiler: aosp-clang/master/clang-r433403
        defconfig: joyeuse_defconfig
        image: Image.gz-dtb

    - name: Release build
  uses: ncipollo/release-action@v1
  with:
    artifacts: ${{ steps.build.outputs.outfile }}
    token: ${{ secrets.GITHUB_TOKEN }}
