name: Greet new contributors :)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           pr-message: 'Thank you for submitting your first Pull Request!'
           issue-message: 'We Will try to Fix the Issue as fast as possible!'


   
