name: Add to Contributors
on:
  push:
    branches:
    - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Adding this new user to Contributors...'
